import os

import pandas as pd
import requests
import yfinance as yf
from openai import OpenAI

# 1. Environment Secrets
telegram_token = os.environ.get("TELEGRAM_BOT_TOKEN")
chat_id = os.environ.get("TELEGRAM_CHAT_ID")
nvidia_key = os.environ.get("NVIDIA_API_KEY")

if not nvidia_key:
    raise ValueError("NVIDIA_API_KEY is missing from environment variables!")

# 2. Read Predictions generated by Ara across your 100+ stock universe
df = pd.read_csv("predictions.csv")

# Grab the top 5 predicted winners
top_stocks = (
    df.head(5)["symbol"].tolist() if "symbol" in df.columns else df.head(5)["ticker"].tolist()
)
stocks_str = ", ".join(top_stocks)

# 3. Pull News Headlines via yfinance
news_context = ""
for ticker in top_stocks:
    try:
        stock = yf.Ticker(ticker)
        news_items = stock.news[:3]
        if news_items:
            news_context += f"\nNews for {ticker}:\n"
            for item in news_items:
                title = item.get(
                    "title", item.get("content", {}).get("title", "No headline available")
                )
                news_context += f"- {title}\n"
        else:
            news_context += f"\nNews for {ticker}:\n- No recent major headlines found.\n"
    except Exception as e:
        news_context += f"\nNews for {ticker}:\n- Could not fetch news: {e}\n"

# 4. Initialize NVIDIA NIM Client
client = OpenAI(base_url="https://integrate.api.nvidia.com/v1", api_key=nvidia_key)

prompt = f"""Ara AI evaluated a universe of 100+ stocks and ranked these as the top expected daily performers: {stocks_str}.

Based on the market context and news headlines below, explain what fundamental catalysts or market momentum might be driving these top rankings. Keep the summary sharp and concise.

Context/News:
{news_context}"""

# 5. Generate completion via DeepSeek V4 Pro on NVIDIA NIM
completion = client.chat.completions.create(
    model="deepseek-ai/deepseek-v4-pro-0813",
    messages=[
        {"role": "system", "content": "You are a sharp, concise quantitative financial analyst."},
        {"role": "user", "content": prompt},
    ],
    temperature=1,
    top_p=0.95,
    max_tokens=2048,
    seed=42,
    extra_body={"chat_template_kwargs": {"thinking": False}},
    stream=False,
)

analysis = completion.choices[0].message.content

# 6. Post Report to Telegram
message = f"📈 **Daily Quant Predictions (100+ Universe)** 📈\n\n**Top Picks:** {stocks_str}\n\n**DeepSeek Catalyst Analysis:**\n{analysis}"

requests.post(
    f"https://api.telegram.org/bot{telegram_token}/sendMessage",
    json={"chat_id": chat_id, "text": message, "parse_mode": "Markdown"},
)
